version: '3.8'

services:
  db:
    build: ./backend
    container_name: resa-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resa-db
    volumes:
      - ./backend/init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: task_manager_api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: resa-db
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data: